# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-actions@release/v2
      env:
        BASE_BRANCH: master
        BRACH: gh-pages
        FOLDER: dist/ai-position
        BUILD_SCRIPT: npm i && npm run build:github && cp dist/ai-position/index.html dist/ai-position/404.html
